language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq $EMACS
  - sudo apt-get install -qq markdown
before_script:
  - $EMACS --version
script:
  - make test gh-pages-push emacs=$EMACS git_user_name=travis git_user_email=8slashes+travis@gmail.com
